ui: listview: fix log::info errors
This commit fixes the errors below, introduced in "Move from
`ScrollBase` to `scroll` module" [1]. As noted by the rust docs [2],
named arguments should be used in the format

```rust
log::info!("content len: {content_len}", content_len=content_len);
```

As this provides no advantage over unnamed args, use them for
conciseness with the rest of the project.

error: there is no argument named `content_len`
  --> src/ui/listview.rs:88:34
   |
88 |         log::info!("content len: {content_len}");
   |                                  ^^^^^^^^^^^^^

error: there is no argument named `loaded`
   --> src/ui/listview.rs:100:35
    |
100 |         log::info!("can paginate: {loaded}");
    |                                   ^^^^^^^^

error: could not compile `ncspot` due to 2 previous errors

[1] - Move from `ScrollBase` to `scroll` module (adf8da2f)
[2] - https://doc.rust-lang.org/std/fmt/#named-parameters

Signed-off-by: Isabella Basso <isabbasso@riseup.net>